# Generated by Django 5.1.6 on 2025-02-07 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='A',
        ),
        migrations.DeleteModel(
            name='B',
        ),
        migrations.DeleteModel(
            name='C',
        ),
        migrations.DeleteModel(
            name='D',
        ),
        migrations.DeleteModel(
            name='E',
        ),
    ]
